class PixverseClient:
    def __init__(self, api_key: str):
        ...

    def upload_image(self, image_path: str) -> int:
        ...

    def generate_image2video(self, img_id: int, prompt: str, bundle_id: str, user_id: str) -> str:
        ...

    def generate_text2video(self, prompt: str, bundle_id: str, user_id: str) -> str:
        ...

    def get_status(self, generation_id: str, bundle_id: str, user_id: str) -> dict:
        ...
